apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mainapiowner
  description: mainapi owner
spec:
  type: business-unit
  profile:
    displayName: main API Team
  children:
    - other

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mainapi
  description: |
    Globalcorp user authentication and banking API.
  links:
    - title: Website
      url: http://harness.io
  annotations:
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/module/cd/orgs/default/projects/globalcorp/pipelines/GoodApi/pipeline-studio?storeType=INLINE

  tags:
    - globalcorp
spec:
  type: service
  owner: mainapiowner
  lifecycle: experimental
